version: "3.8"
services:
  warungpintar-db-migration-production:
    container_name: ${DB_MIGRATION_CONTAINER}
    hostname: ${DB_MIGRATION_HOST}
    image: "${DB_MIGRATION_IMAGE}:${DB_MIGRATION_IMAGE_TAG}"
    environment:
      BACKEND_STAGE: ${BACKEND_STAGE}
    networks:
      - warungpintar-environment-production

networks:
  warungpintar-environment-production:
    external: true
    name: warungpintar-environment-production
